import Head from 'next/head';
import Script from 'next/script';
import Navbar from '../components/Navbar';
import Expertise from './expertise';
import Footer from './footer';
import Homepage from './homepage';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Franco's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script id="script" src="https://smtpjs.com/v3/smtp.js" />
      </Head>

      <Navbar/>
      <Homepage/>
      <Expertise/>
      <Footer/>
    </div>
  )
}
